import { ListView } from "std-widgets.slint";
import { Theme } from "theme.slint";

export component InstanceList inherits Rectangle {
    background: Theme.secondary;

    ListView {
        width: 100%;
        height: 100%;

        for name in ["Instance"]: Rectangle {
            height: 68px;
            width: 90%;
            x: (parent.width - self.width) / 2;
            background: transparent;

            Rectangle {
                y: 4px;
                height: 60px;
                width: parent.width;
                background: Theme.background;
                border-radius: 8px;

                Text {
                    text: name;
                    color: Theme.text;
                    horizontal-alignment: left;
                    vertical-alignment: top;
                }
            }
        }
    }
}