import { Button, VerticalBox } from "std-widgets.slint";
import { Sidebar } from "sidebar.slint";
import { Theme } from "theme.slint";
export { Theme }
import { InstanceList } from "instance_list.slint";

import { ProgressOverlay, ProgressStage } from "dialogues/progress.slint";
export { ProgressStage }

export component AppWindow inherits Window {
    callback open_folder();
    callback open_theme_debug();
    callback preview_progress();

    in property <bool> dev: false;
    in property <string> git_hash: "";

    in property <bool> progress-active: false;
    in property <float> progress-value: 0.0;
    in property <string> progress-stage: "";
    in property <[ProgressStage]> progress-stages: [];

    title: dev ? @tr("Devurich - {}", root.git_hash)
    : @tr("Lazurich");
    icon: @image-url("../assets/logo.png");
    min-width: 600px;
    min-height: 400px;
    background: Theme.background;


    menu-bar := MenuBar {
        Menu {
            title: @tr("Instance");
            MenuItem { title: @tr("Create New"); activated => { /* ... */ } }
        }
        if dev: Menu {
            title: @tr("Developer");
            MenuItem { title: @tr("Open theme debug"); activated => { open_theme_debug(); } }
            MenuItem { title: @tr("Open source folder"); activated => { open_folder(); } }
            MenuItem { title: @tr("Preview progress overlay"); activated => { preview_progress(); } }
        }
    }

    HorizontalLayout {
        height: 100%;
        spacing: 20px;
        Sidebar {}
        Rectangle {
            background: Theme.secondary;
            horizontal-stretch: 1;
            InstanceList {
                horizontal-stretch: 1;
            }
        }
    }

    ProgressOverlay {
        width: 100%;
        height: 100%;
        active: root.progress-active;
        progress: root.progress-value;
        current-stage: root.progress-stage;
        stages: root.progress-stages;
    }
}