import { Button, VerticalBox } from "std-widgets.slint";
import { Sidebar } from "sidebar.slint";
import { Theme } from "theme.slint";
export { Theme }
import { InstanceList, InstanceRow } from "instance_list.slint";
export { InstanceRow }
import { InstanceEdit } from "instance_edit.slint";
import { ProgressOverlay, ProgressStage } from "dialogues/progress.slint";
export { ProgressStage }
import { ErrorOverlay } from "dialogues/error.slint";


export component AppWindow inherits Window {
    callback open_folder();
    callback open_theme_debug();
    callback preview_progress();
    callback preview_error();
    callback launch_instance(string);
    callback edit_instance(string);
    in property <bool> dev: false;
    in property <string> git_hash: "";

    in property <bool> progress-active: false;
    in property <float> progress-value: 0.0;
    in property <string> progress-stage: "";
    in property <[ProgressStage]> progress-stages: [];
    in property <[InstanceRow]> instance-list: [];

    in property <string> instance-edit-name: @tr("You shouldn't be seeing this! - Placeholder instance name");
    in property <bool> instance-edit-visible: false;

    in property <bool> error-active: false;
    in property <string> error-text: "";

    title: dev ? @tr("Devurich - {}", root.git_hash)
    : @tr("Lazurich");
    icon: @image-url("../assets/logo.png");
    min-width: 600px;
    min-height: 400px;
    background: Theme.background;

    menu-bar := MenuBar {
        Menu {
            title: @tr("Instance");
            MenuItem { title: @tr("Create New"); activated => { /* ... */ } }
        }
        if dev: Menu {
            title: @tr("Developer");
            MenuItem { title: @tr("Open theme debug"); activated => { open_theme_debug(); } }
            MenuItem { title: @tr("Open source folder"); activated => { open_folder(); } }
            MenuItem { title: @tr("Preview progress overlay"); activated => { preview_progress(); } }
            MenuItem { title: @tr("Preview error overlay"); activated => { preview_error(); } }
        }
    }

    HorizontalLayout {
        height: 100%;
        spacing: 20px;
        Sidebar {}
        Rectangle {
            background: Theme.secondary;
            horizontal-stretch: 1;
            InstanceList {
                horizontal-stretch: 1;
                instances: root.instance-list;
                edit(id) => { root.edit_instance(id); }
                visible: !root.instance-edit-visible;
            }
            InstanceEdit {
                horizontal-stretch: 1;
                instance-name: root.instance-edit-name;
                visible: root.instance-edit-visible;
            }
        }
    }

    ProgressOverlay {
        width: 100%;
        height: 100%;
        active: root.progress-active;
        progress: root.progress-value;
        current-stage: root.progress-stage;
        stages: root.progress-stages;
    }

    ErrorOverlay {
        width: 100%;
        height: 100%;
        active: root.error-active;
        message: root.error-text;
    }
}