import { Button, VerticalBox } from "std-widgets.slint";
import { Sidebar } from "sidebar.slint";
import { Theme } from "theme.slint";
export { Theme }
import { InstanceList } from "instance_list.slint";

export component AppWindow inherits Window {
    callback b_launch_game();
    callback open_theme_debug();
    in property <bool> dev: false;

    title: dev ? "Lazurich (Developer)"
    : "Lazurich";
    icon: @image-url("../assets/logo.png");
    min-width: 600px;
    min-height: 400px;
    background: Theme.background;

    menu-bar := MenuBar {
        Menu {
            title: "Instance";
            MenuItem { title: "Create New"; activated => { /* ... */ } }
        }
        if dev: Menu {
            title: "Developer";
            MenuItem { title: "Open theme debug"; activated => { open_theme_debug(); } }
        }
    }

    HorizontalLayout {
        height: 100%;
        spacing: 20px;
        Sidebar {}
        Rectangle {
            background: Theme.secondary;
            horizontal-stretch: 1;
            InstanceList {
                horizontal-stretch: 1;
            }
        }
    }
}