import { Button, VerticalBox } from "std-widgets.slint";
import { Theme } from "theme.slint";

component SidebarButton inherits TouchArea {
    in property <image> icon;
    callback activate();

    width: 12%;
    height: self.width;

    clicked => { root.activate(); }

    Rectangle {
        border-radius: 6px;
        background: parent.pressed
            ? Theme.primary
            : parent.has-hover
                ? Theme.button.brighter(0.5)
                : Theme.button;
        animate background { duration: 100ms; }

        Image {
            source: icon;
            width: parent.width;
            height: parent.height;

            colorize: root.pressed
                ? Theme.button-press
                : white;

            animate colorize { duration: 100ms; }
        }
    }
}

export component Sidebar inherits Rectangle {
//    width: 64px;
    width: Theme.sidebar_width.to-float() * 1px;
    background: Theme.sidebar;
    height: 100%;

    VerticalBox {
        SidebarButton {
            icon: Theme.dashboard-icon;
        }
        SidebarButton {
            icon: Theme.list-icon;
        }
        Rectangle { vertical-stretch: 1; } // spacer
        SidebarButton {
            icon: Theme.skin-icon;
        }
        SidebarButton {
            icon: Theme.settings-icon;
        }
    }
}
