export global Theme {
    in-out property <color> primary: #7c3aed;
    in-out property <color> secondary: #2a2a3a;
    in-out property <color> background: #1e1e2e;
    in-out property <color> text: white;
    in-out property <color> button: #0377fc;
    in-out property <color> sidebar: #2c3036;

    in-out property <color> fail: #ed182a;
    in-out property <color> warning: #fae019;

    in-out property <color> button-press: #7c3aed;

    in-out property <image> dashboard-icon: @image-url("../theme/assets/dashboard.png");
    in-out property <image> list-icon: @image-url("../theme/assets/list.png");
    in-out property <image> settings-icon: @image-url("../theme/assets/settings.png");
    in-out property <image> skin-icon: @image-url("../theme/assets/skin.png");

    in-out property <string> sidebar_width: 64;
}