export global Theme {
    in-out property <color> primary: #7c3aed;
    in-out property <color> secondary: #2a2a3a;
    in-out property <color> background: #1e1e2e;
    in-out property <color> text: white;

    in-out property <image> dashboard-icon: @image-url("../theme/assets/dashboard.png");
    in-out property <image> list-icon: @image-url("../theme/assets/list.png");
    in-out property <image> settings-icon: @image-url("../theme/assets/settings.png");
    in-out property <image> skin-icon: @image-url("../theme/assets/skin.png");
}